# Gnuplot script file automatically generated by Plot2D.java
# Plotting data in files ??
set term png
set xlabel "null"
set ylabel "null"
set output "./output/linear.png"
plot "./output/linear_null" title "null" with linespoints 