# Gnuplot script file automatically generated by Plot2D.java
# Plotting data in files ??
set term png
set xlabel "null"
set ylabel "null"
set output "./output/predator_prey.png"
plot "./output/predator_prey_predator" title "predator" with linespoints , "./output/predator_prey_prey" title "prey" with linespoints 